#!/bin/bash
# Copyright (C) 2018 MariaDB Corporation
# Creates a templetised master-slave cluster fronted by MaxScale in Kubernetes
# User-defined parameters are "application" and "environment"

function print_usage() {
    echo "Usage: "
    echo "create-masterslave-cluster.sh -a <application> -e <environment> [<options>]"
    echo ""
    echo "Required options: "
    echo "         -a <application name>"
    echo "         -e <environment name>"
    echo ""
    echo "<application name>-<environment name> will be prepended to kubernetes instance names"
    echo ""
    echo "Supported options: "
    echo "         -u <database user>, default: mariadb-admin"
    echo "         -p <database password>, default: autogenerated"
    echo "         --repl-user <replication user>, default: repl"
    echo "         --repl-password <replication password>, default: autogenerated"
    echo "         --dry-run generate yaml definitions only"
    echo "         --delete delete the cluster"
    echo "         -h print this screen"
    exit 1
}

function parse_options() {
    APP=""
    ENV=""
    DBUSER="admin"
    DBPWD=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
    REPLUSER="repl"
    REPLPWD=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
    DRY_RUN=""
    VOLSIZE="1"
    DELETE="no"

    while [[ $# -gt 0 ]]
    do

    key="$1"
    case $key in
        (-a|--app)
        APP="$2"
        shift
        shift
        ;;
        (-e|--env)
        ENV="$2"
        shift
        shift
        ;;
        (-u|--db-user)
        DBUSER="$2"
        shift
        shift
        ;;
        (-p|--db-pass)
        DBPWD="$2"
        shift
        shift
        ;;
        (--dry-run)
        DRY_RUN="--dry-run -o yaml"
        shift
	;;
	(-d|--delete)
	DELETE="yes"
	shift
        ;;
        (-h|*)
        print_usage
        ;;
    esac
    done

    if [[ -z "$APP" ]]; then
       print_usage
    fi

    if [[ -z "$ENV" ]]; then
       print_usage
    fi

    LABEL="$APP-$ENV"
}

function expand_templates() {
    # copy template files to a temp directory
    TEMPDIR=$(mktemp -d)
    cp -r "$DIR/templates" "$TEMPDIR"

    for filename in $TEMPDIR/templates/*.yaml; do
        sed -e "s/{{MARIADB-LABEL}}/$LABEL/g" \
            -e "s/{{MARIADB-VOLUME-SIZE}}/$VOLSIZE/g" \
            -e "s/{{ADMIN_USERNAME}}/$(echo -n $DBUSER | base64)/g" \
            -e "s/{{ADMIN_PASSWORD}}/$(echo -n $DBPWD | base64)/g" \
            -e "s/{{REPLICATION_USERNAME}}/$(echo -n $REPLUSER | base64)/g" \
            -e "s/{{REPLICATION_PASSWORD}}/$(echo -n $REPLPWD | base64)/g" \
            -i $filename
    done

    TEMPLATE="$TEMPDIR/templates"
}

parse_options "$@"

# get directory of script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
KUBECTL=kubectl

if [ "$DELETE" == "yes" ]; then
   set -e

   $KUBECTL delete svc,sts,deployment,secret -l mariadb=$LABEL
   $KUBECTL delete pvc -l server.mariadb=$LABEL

   exit 0
fi

expand_templates

if [ "$DRY_RUN" == "" ]; then
   $KUBECTL delete configmap mariadb-config 2> /dev/null
fi

set -e

# compress the state store in order for it to fit in a config map
tar czf "$TEMPLATE"/config/state-store.tar.gz -C "$TEMPLATE"/config/state-store .
rm -R -f "$TEMPLATE"/config/state-store

# create configmaps for the configurations of the two types of service
$KUBECTL create configmap mariadb-config --from-file="$TEMPLATE"/config/ $DRY_RUN
if [ "$DRY_RUN" != "" ]; then
   echo "---"
fi

# create the secret that holds user names and passwords
$KUBECTL create -f "$TEMPLATE"/mariadb-secret.yaml $DRY_RUN
if [ "$DRY_RUN" != "" ]; then
   echo "---"
fi

$KUBECTL create -f "$TEMPLATE"/state-store.yaml $DRY_RUN
if [ "$DRY_RUN" != "" ]; then
   echo "---"
fi

# all mariadb servers are available, create maxscale instance
$KUBECTL create -f "$TEMPLATE"/maxscale.yaml $DRY_RUN
if [ "$DRY_RUN" != "" ]; then
   echo "---"
fi

# create the master/slave cluster as a stateful set (including service definitions)
$KUBECTL create -f "$TEMPLATE"/masterslave.yaml $DRY_RUN
if [ "$DRY_RUN" != "" ]; then
   echo "---"
fi

# cleanup temporary files
rm -R -f "$TEMPDIR"
# done
