RESET MASTER;
STOP SLAVE;
CHANGE MASTER TO 
    MASTER_HOST='<<MASTER_HOST>>', 
	MASTER_PORT=3306, 
	MASTER_USER='{{ .Values.REPLICATION_USERNAME }}', 
	MASTER_PASSWORD='{{ .Values.REPLICATION_PASSWORD }}', 
	MASTER_USE_GTID=current_pos,
	MASTER_CONNECT_RETRY=0;

START SLAVE;

SET GLOBAL max_connections=10000;
SET GLOBAL gtid_strict_mode=ON;
