CREATE DATABASE IF NOT EXISTS test;

CREATE USER IF NOT EXISTS '{{ZEPPELIN_USER}}'@'%' IDENTIFIED BY '{{ZEPPELIN_PASSWORD}}';
GRANT ALL ON bookstore.* TO '{{ZEPPELIN_USER}}'@'%';
GRANT ALL ON test.* TO '{{ZEPPELIN_USER}}'@'%';
GRANT ALL ON benchmark.* TO '{{ZEPPELIN_USER}}'@'%';
GRANT ALL ON infinidb_vtable.* TO '{{ZEPPELIN_USER}}'@'%'; 
 
#TODO: find who creates this anonymous user in columnstore and why.
DELETE FROM mysql.user WHERE User=''; 

CREATE USER IF NOT EXISTS '{{ADMIN_USER}}'@'127.0.0.1' IDENTIFIED BY '{{ADMIN_PASSWORD}}';
CREATE USER IF NOT EXISTS '{{ADMIN_USER}}'@'%' IDENTIFIED BY '{{ADMIN_PASSWORD}}';
GRANT ALL ON *.* TO '{{ADMIN_USER}}'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL ON *.* TO '{{ADMIN_USER}}'@'%' WITH GRANT OPTION;
