RESET MASTER;
STOP SLAVE;
CHANGE MASTER TO 
    MASTER_HOST='{{MASTER_HOST}}', 
	MASTER_PORT=3306, 
	MASTER_USER='{{REPLICATION_USER}}', 
	MASTER_PASSWORD='{{REPLICATION_PASSWORD}}', 
	MASTER_USE_GTID=current_pos,
	MASTER_CONNECT_RETRY=3;

CHANGE MASTER TO MASTER_USE_GTID=curren_pos;
START SLAVE;

SET GLOBAL max_connections=10000;
SET GLOBAL gtid_strict_mode=ON;

