apiVersion: v1
kind: Service
metadata:
  name: {{APPLICATION}}-{{ENVIRONMENT}}-mariadb
  labels:
    mariadb: {{APPLICATION}}-{{ENVIRONMENT}}
spec:
  ports:
  - name: maxscale-readwrite
    port: 4006
    targetPort: 4006
  - name: maxscale-readonly
    port: 4008
    targetPort: 4008
  selector:
    mariadb: {{APPLICATION}}-{{ENVIRONMENT}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{APPLICATION}}-{{ENVIRONMENT}}-mdb-mxs
spec:
  selector:
    matchLabels:
      mariadb: {{APPLICATION}}-{{ENVIRONMENT}}
  serviceName: {{APPLICATION}}-{{ENVIRONMENT}}-mdb-clust
  replicas: 1
  template:
    metadata:
      labels:
        mariadb: {{APPLICATION}}-{{ENVIRONMENT}}
    spec:
      initContainers:
      - name: init-maxscale
        image: mariadb/server:10.3
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - /etc/maxscale-cfg
          - "2"
        volumeMounts:
          - mountPath: /mnt/secrets
            name: mariadb-secrets-vol
            readOnly: true
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
          - mountPath: /etc/maxscale-cfg
            name: mariadb-config-vol
      containers:
      - args:
        - maxscale
        - -d
        - -U
        - maxscale
        - --configdir=/etc/maxscale-cfg
        image: mariadb/maxscale:latest
        name: maxscale
        ports:
        - containerPort: 4006
        - containerPort: 4008
        resources: {}
        volumeMounts:
        - mountPath: /etc/maxscale-cfg
          name: mariadb-config-vol
      restartPolicy: Always
      volumes:
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{APPLICATION}}-{{ENVIRONMENT}}-mariadb-secret
