# Headless service for stable DNS entries for StatefulSet members
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.LABEL }}-mariadb
  labels:
    mariadb: {{ .Values.LABEL }}
    endpoint.mariadb: {{ .Values.LABEL }}
spec:
  ports:
  - name: mariadb
    port: 3306
    targetPort: 3306
  selector:
    mariadb: {{ .Values.LABEL }}
---   
# a StatefulSet for the master/slave cluster 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.LABEL }}-mdb-ms
  labels:
    mariadb: {{ .Values.LABEL }}
    server.mariadb: {{ .Values.LABEL }}
spec:
  selector:
    matchLabels:
      mariadb: {{ .Values.LABEL }}
      server.mariadb: {{ .Values.LABEL }}
  serviceName: {{ .Values.LABEL }}-mariadb
  replicas: 1
  template:
    metadata:
      labels:
        server.mariadb: {{ .Values.LABEL }}
        mariadb: {{ .Values.LABEL }}
    spec:
      initContainers:
      # simulate a state store client to bootstrap self as active master
      - name: init-get-master
        image: node:alpine
        command: ["/bin/sh"]
        args: ["-c", "echo 'localhost' > /mnt/config-map/master"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /mnt/config-map
            name: mariadb-config-vol
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
      # runs an initialization script to prepare the correct startup configuration
      - name: init-masterslave
        image: mariadb:10.3
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - masterslave
        volumeMounts:
          - mountPath: /mnt/secrets
            name: mariadb-secrets-vol
            readOnly: true
          - name: mariadb-entrypoint-vol
            mountPath: /docker-entrypoint-initdb.d
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
          - mountPath: /mnt/config-map
            name: mariadb-config-vol
      containers:
      - command:
        # start a mariadb instance
        - bash
        - /mnt/config-map/start-mariadb-instance.sh 
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "Y"
        image: mariadb:10.3
        name: mariadb-server
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - name: mariadb-entrypoint-vol
          mountPath: /docker-entrypoint-initdb.d
        - name: mariadb-config-vol
          mountPath: /mnt/config-map
        # a permanent volume for data storage
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
      - name: mariadb-entrypoint-vol 
        emptyDir: {}
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: {{ .Values.LABEL }}-mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{ .Values.LABEL }}-mariadb-secret
  # ensures persistent volumes end up on the same pod
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        mariadb: {{ .Values.LABEL }}
        server.mariadb: {{ .Values.LABEL }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.MARIADB_VOLUME_SIZE }}
 
