# Copyright (C) 2018, MariaDB Corporation
#
# Defines a standalone configuration in a StatefulSet behind. The number of
# replicas should always be 1.

# External service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    mariadb: {{ .Release.Name }}
    entrypoint.mariadb: {{ .Release.Name }}
    {{- if .Values.mariadb.cluster.id }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
    {{- end }}
    {{- if .Values.mariadb.cluster.labels }}
{{ toYaml .Values.mariadb.cluster.labels | indent 4 }}
    {{- end }}
    {{- if .Values.mariadb.server.labels }}
{{ toYaml .Values.mariadb.server.labels | indent 4 }}
    {{- end }}
spec:
  ports:
  - name: mariadb
    port: {{ .Values.mariadb.server.port }}
    targetPort: {{ .Values.mariadb.server.port }}
  selector:
    server.mariadb: {{ .Release.Name }}
---
# a StatefulSet for the master/slave cluster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mdb-ms
  labels:
    mariadb: {{ .Release.Name }}
    server.mariadb: {{ .Release.Name }}
    {{- if .Values.mariadb.cluster.id }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
    {{- end }}
spec:
  selector:
    matchLabels:
      server.mariadb: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-mariadb
  replicas: 1
  template:
    metadata:
      labels:
        mariadb: {{ .Release.Name }}
        server.mariadb: {{ .Release.Name }}
        {{- if .Values.mariadb.cluster.id }}
        id.mariadb: "{{ .Values.mariadb.cluster.id }}"
        {{- end }}
      {{- if or (.Values.mariadb.cluster.annotations) (.Values.mariadb.server.annotations) }}
      annotations:
      {{- end }}
      {{- if .Values.mariadb.cluster.annotations }}
{{ toYaml .Values.mariadb.cluster.annotations | indent 8 }}
      {{- end }}
      {{- if .Values.mariadb.server.annotations }}
{{ toYaml .Values.mariadb.server.annotations | indent 8 }}
      {{- end }}
    spec:
      initContainers:
      # simulate a state store client to bootstrap self as active master
      - name: init-get-master
        image: {{ .Values.mariadb.server.image }}
        command: ["/bin/sh"]
        args: ["-c", "echo 'localhost' > /mnt/config-map/master"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /mnt/config-map
            name: mariadb-config-vol
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
      # runs an initialization script to prepare the correct startup configuration
      - name: init-masterslave
        image: {{ .Values.mariadb.server.image }}
        command:
          - bash
          - /mnt/config-template/init-configurations.sh
          - masterslave
        volumeMounts:
          - mountPath: /mnt/secrets
            name: mariadb-secrets-vol
            readOnly: true
          - name: mariadb-entrypoint-vol
            mountPath: /docker-entrypoint-initdb.d
          - mountPath: /mnt/config-template
            name: mariadb-configtemplate-vol
          - mountPath: /mnt/config-map
            name: mariadb-config-vol
      containers:
      - command:
        # start a mariadb instance
        - bash
        - /mnt/config-map/start-mariadb-instance.sh
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "Y"
        image: {{ .Values.mariadb.server.image }}
        name: mariadb-server
        ports:
        - containerPort: {{ .Values.mariadb.server.port }}
        {{- if or (.Values.mariadb.server.resources.limits.cpu) (.Values.mariadb.server.resources.limits.memory) (.Values.mariadb.server.resources.requests.cpu) (.Values.mariadb.server.resources.requests.memory) }}
        resources:
        {{- end }}
          {{- if or (.Values.mariadb.server.resources.requests.cpu) (.Values.mariadb.server.resources.requests.memory) }}
          requests:
          {{- end }}
            {{- if .Values.mariadb.server.resources.requests.cpu }}
            cpu: {{ .Values.mariadb.server.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.mariadb.server.resources.requests.memory }}
            memory: {{ .Values.mariadb.server.resources.requests.memory }}
            {{- end }}
          {{- if or (.Values.mariadb.server.resources.limits.cpu) (.Values.mariadb.server.resources.limits.memory) }}
          limits:
          {{- end }}
            {{- if .Values.mariadb.server.resources.limits.cpu }}
            cpu: {{ .Values.mariadb.server.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.mariadb.server.resources.limits.memory }}
            memory: {{ .Values.mariadb.server.resources.limits.memory }}
            {{- end }}
        volumeMounts:
        {{- if .Values.mariadb.server.backup.claimName }}
        - name: backup-data-storage
          mountPath: /backup
        {{- end }}
        - name: mariadb-entrypoint-vol
          mountPath: /docker-entrypoint-initdb.d
        - name: mariadb-config-vol
          mountPath: /mnt/config-map
        # a permanent volume for data storage
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
      {{- if .Values.mariadb.server.backup.claimName }}
      - name: backup-data-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mariadb.server.backup.claimName }}
      {{- end }}
      - name: mariadb-entrypoint-vol
        emptyDir: {}
      - name: mariadb-config-vol
        emptyDir: {}
      - name: mariadb-configtemplate-vol
        configMap:
          name: {{ .Release.Name }}-mariadb-config
      - name: mariadb-secrets-vol
        secret:
          secretName: {{ .Release.Name }}-mariadb-secret
  # ensures persistent volumes end up on the same pod
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        mariadb: {{ .Release.Name }}
        storage.mariadb: {{ .Release.Name }}
        {{- if .Values.mariadb.cluster.id }}
        id.mariadb: "{{ .Values.mariadb.cluster.id }}"
        {{- end }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mariadb.server.storage.size }}
      {{- if .Values.mariadb.server.storage.class }}
      storageClassName: {{ .Values.mariadb.server.storage.class }}
      {{- end }}
