# Copyright (C) 2018, MariaDB Corporation
#
# Defines a state store server that maintains (through heartbeat calls
# from each pod in a MariaDB cluster on a regular scheduled interval):
#   * a list of MaxScale instances
#   * a list of MariaDB server instances
#   * a reference to a single active MaxScale instance
#   * a reference to a single Master instance
#
# The number of replicas should be exactly 1.

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mdb-state
  labels:
    mariadb: {{ .Release.Name }}
    state-store.mariadb: {{ .Release.Name }}
    {{ if .Values.mariadb.cluster.id }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
    {{ end }}
spec:
  selector:
    state-store.mariadb: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mdb-state
  labels:
    mariadb: {{ .Release.Name }}
    state-store.mariadb: {{ .Release.Name }}
    {{ if .Values.mariadb.cluster.id }}
    id.mariadb: "{{ .Values.mariadb.cluster.id }}"
    {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      state-store.mariadb: {{ .Release.Name }}
  template:
    metadata:
      labels:
        mariadb: {{ .Release.Name }}
        state-store.mariadb: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.mariadb.statestore.image }}
        command: ["/bin/sh"]
        args: ["-c", "cd /root; node ./server.js"]
        imagePullPolicy: IfNotPresent
        name: state-store
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mariadb-configtemplate-vol
            mountPath: /mnt/config-template
      volumes:
      - name: mariadb-configtemplate-vol
        configMap:
          name: {{ .Release.Name }}-mariadb-config
      restartPolicy: Always
